### ISSUE TITLE
add support for other k8s resources

### ISSUE THREAD

**Issue by frankgreco** [frankgreco/kubenforce#2]
The goal is to have have the Kubernetes kind defined in the ConfigPolicy Resource Configuration as follows:

```yaml
apiVersion: k8s.io/v1
kind: ConfigPolicy
metadata:
  name: policy
  namespace: default
spec:
  apiVersion: v1
  kind: Service
```

There are 2 different approaches to do this:

### completely dynamic
make a call to the k8s api based on the kind that is specified in the config. However, to do this, the kind name and api version of that kind would need to be known. For example, for `kind: Pod`, the name would be pods and the api version would be v1. This info should be available from a series of api calls.
#### pros:
* completely dynamic
* could potentially support custom kinds through TPR
#### cons:
* could be tricky. Depends on if there is an efficient way to dynamically parse through the returned spec.

### hardcoded resources
hardcode the resources and act based on which one was set
#### pros:
* straight forward
#### cons:
* potentially very limited
